name: dart_parsing
description: "Composable, reusable, and extensible parsers for Dart."
version: 0.1.1
repository: https://github.com/viniciusaro/dart-parsing

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.25.7
  equatable: ^2.0.5  

dependencies:
  collection: ^1.19.0
  unorm_dart: ^0.3.0
