name: benchmarking
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  benchmark_harness: ^2.2.2
  equatable: ^2.0.5
  petitparser: ^7.0.1
  dart_parsing: 
    path: ../

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
